Improved git-feature script
It now checks for a ~/.git-feature file for the needed variables

diff --git a/git-feature b/git-feature
--- a/git-feature
+++ b/git-feature
@@ -5,34 +5,41 @@
 #
 
 _get_jira_ticket_for_description () {
-  if [[ -n "$USERNAME" || -n "$PASSWORD" || -n "$JIRA_URL" ]]; then
-    ticket=$(curl -s -u $USERNAME:$PASSWORD $JIRA_URL$1)
-    summary=$(printf "%s" "$ticket" | jq -M -r '.fields.summary')
-    [[ -n "$summary" ]] && git config branch.$1.description "$summary"
+  local summary=$(curl -s -u $USERNAME:$PASSWORD $JIRA_URL$1 | jq -M -r '.fields.summary')
+  if [[ -n "$summary" ]]; then
+    git config branch.$1.description "$summary"
+    [[ -n "$(type -p 'git-branches')" ]] && git branches
   fi
 }
 
-if [[ $# -ne 1 ]]; then
-  printf "Usage:  git feature <ticket_id>\n\tThis script uses \$USERNAME, \$PASSWORD, and \$JIRA_URL environment variables\n"
-elif [[ -z "$(type -t jq)" ]]; then
-  printf "This script requires jq to be installed in order to parse the JSON response from JIRA.\n"
-elif [[ -z "$USERNAME" || -z "$PASSWORD" || -z "$JIRA_URL" ]]; then
-  printf "Must export \$USERNAME, \$PASSWORD, and \$JIRA_URL environment variables.\n"
-else
-  if [[ -n "$(git branch --all | grep $1)" ]]; then
-    if [[ -z "$(git config branch.$1.description)" ]]; then
-      read -e -r -p "$1 already exists but has no description. Try to get its JIRA summary? [y/n]: " choice && printf "\n"
-      if [[ "$choice" =~ ^y|Y ]]; then
-        _get_jira_ticket_for_description "$1"
-      fi
-    else
-      printf "$1 has already been created and has a description.\n"
-    fi
+_print_usage () {
+  printf "Usage:  git feature <ticket_id>\n"
+  printf "\tThis script uses \$USERNAME, \$PASSWORD, and \$JIRA_URL environment variables. An optional \$PREFIX\n"
+  printf "\tvariable can be set for your JIRA project prefix so that you can simply provide the ticket number\n"
+  printf "\tas the only argument to this script. If \$PREFIX is not used then you must provide the full ticket\n"
+  printf "\tname (e.g., XYZ-1234). \$PREFIX should just be letters without a dash. These variables can be set in\n"
+  printf "\tyour .bashrc or in a file in your home directory called '.git-feature'.\n"
+}
+
+[[ $# -ne 1 ]] && _print_usage && exit 0
+[[ -z "$(type -t jq)" ]] && printf "jq is required to parse the response from JIRA.\n" && exit 0
+if [[ "$1" =~ ^[A-Z]*-?[0-9]+$ ]]; then
+  br="$1"
+  [[ -f ~/.git-feature ]] && source ~/.git-feature
+  [[ -z "$USERNAME" || -z "$PASSWORD" || -z "$JIRA_URL" ]] && _print_usage && exit 1
+  if [[ -n "$PREFIX" ]] && ! [[ "$br" =~ ^[A-Z]+-[0-9]+$ ]]; then
+    [[ "$PREFIX" =~ -$ ]] && br="$PREFIX$br" || br="$PREFIX-$br"
+  fi
+  if [[ -n "$(git branch --all | grep $br)" ]]; then
+    [[ -n "$(git config branch.$br.description)" ]] && printf "$br already exists and has a description.\n" && exit 0
+    read -e -r -p "$br exists without a description. Try to get its JIRA summary? [y/n]: " choice && printf "\n"
+    [[ "$choice" =~ ^y|Y ]] && _get_jira_ticket_for_description "$br"
   else
     git fetch origin master:master
-    git checkout -b "$1" origin/master
-    git push -u origin "$1"
-    _get_jira_ticket_for_description "$1"
+    git checkout -b "$br" origin/master
+    git push -u origin "$br"
+    _get_jira_ticket_for_description "$br"
   fi
-  [[ -n "$(type -p 'git-branches')" ]] && git branches
+else
+  _print_usage
 fi
